variables:
    TXT_S: "\e[35m"
    TXT_CLEAR: "\e[0m"

.unit_test: &unit_test
  script:
    - scripts/bootstrap.sh
    - scripts/build_ci.sh
    - scripts/run_unittests.sh
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /WIP$/
      when: never
  artifacts:
    paths:
      - build_dev/*_junit.txt
    reports:
      junit: build_dev/*_junit.txt

.merge_request: &merge_request
  tags:
    - ubuntu20.04
  script:
    - scripts/bootstrap.sh
    - scripts/build_ci_merge.sh
    - scripts/valgrind_unittests.sh 
  artifacts:
    paths:
      - public
      - build_dev/*_junit.txt
      - build_dev/valgrind-out.txt
    reports:
      junit: build_dev/*_junit.txt

unit_tests:ubuntu20_04:
  <<: *unit_test 
  tags:
    - ubuntu20.04
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

unit_tests:ubuntu18_04:
  <<: *unit_test 
  tags:
    - ubuntu18.04

merge_request:
  <<: *merge_request
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pages:
  <<: *merge_request
  stage: deploy
  # only:
  #  - master
  