.unit_test:
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/libesys/esysbuild/dev.git _ci_dev
    - _ci_dev/scripts/bootstrap.sh
    - cd build_dev
    - cd src
    - cd esysrepo
    - git checkout ${CI_COMMIT_BRANCH}
    - cd ../..
    - src/esysrepo/scripts/build_ci.sh
    - src/esysrepo/scripts/run_unittests.sh
  artifacts:
    paths:
      - build_dev/*.junit
    reports:
      junit: build_dev/*.junit

unit_tests:ubuntu20_04:
  extends: .unit_test
  tags:
    - ubuntu20.04

unit_tests:ubuntu18_04:
  extends: .unit_test
  tags:
    - ubuntu18.04
