@echo off

if not defined PROMPT set PROMPT=$P$G

if defined _ESYSREPO_OLD_VIRTUAL_PROMPT set PROMPT=%_ESYSREPO_OLD_VIRTUAL_PROMPT%

set _ESYSREPO_OLD_VIRTUAL_PROMPT=%PROMPT%
set PROMPT=(esysrepo) %PROMPT%

if defined _ESYSREPO_OLD_VIRTUAL_PATH set PATH=%_ESYSREPO_OLD_VIRTUAL_PATH%
if not defined _ESYSREPO_OLD_VIRTUAL_PATH set _ESYSREPO_OLD_VIRTUAL_PATH=%PATH%

set PATH=%~dp0;%PATH%
