@echo off

if defined _ESYSREPO_OLD_VIRTUAL_PROMPT (
    set "PROMPT=%_ESYSREPO_OLD_VIRTUAL_PROMPT%"
)
set _ESYSREPO_OLD_VIRTUAL_PROMPT=

if defined _ESYSREPO_OLD_VIRTUAL_PATH (
    set "PATH=%_ESYSREPO_OLD_VIRTUAL_PATH%"
)

set _ESYSREPO_OLD_VIRTUAL_PATH=
