set ESYSREPO=%~dp0\..
set ESYSREPO_DOC_OUTPUT_DIR=%~dp0
set DOXYGEN_QUIET=No
set DOXYGEN_WARNINGS=YES
set DOXYGEN_WARN_IF_UNDOCUMENTED=YES
set DOXYGEN_WARN_IF_DOC_ERROR=YES
set DOXYGEN_WARN_LOGFILE=

doxywizard %~dp0\Doxyfile
