// PySwig 0.1.0

#pragma once

#include "esys/repo/version.h"
#include "esys/repo/git/branchtype.h"
#include "esys/repo/git/branch.h"
#include "esys/repo/git/commithash.h"
#include "esys/repo/git/commit.h"
#include "esys/repo/git/remote.h"
#include "esys/repo/progresscallbackbase.h"
#include "esys/repo/gitbase.h"
#include "esys/repo/githelper.h"
#include "esys/repo/git.h"
#include "esys/repo/libgit2/git.h"
#include "esys/repo/manifest/format.h"
#include "esys/repo/manifest/repository.h"
#include "esys/repo/manifest/group.h"
#include "esys/repo/manifest/location.h"
#include "esys/repo/manifest/type.h"
#include "esys/repo/manifest/fileerror.h"
#include "esys/repo/manifest.h"
#include "esys/repo/manifest/filebase.h"
#include "esys/repo/grepo/manifest.h"
#include "pyversion.h"
