#!/bin/bash

SSH_ENV=$HOME/.ssh/environment
GITLAB_RUNNER_KEY_FILE=$HOME/.ssh/gitlab-runner_id_rsa

function start_agent {
	echo "Initialising new SSH agent..."
	/usr/bin/ssh-agent | sed 's/^echo/#echo/' > ${SSH_ENV}
	echo succeeded
	chmod 600 ${SSH_ENV}
	. ${SSH_ENV} > /dev/null
 	/usr/bin/ssh-add;
	if [ -f "${GITLAB_RUNNER_KEY_FILE}" ]; then
		/usr/bin/ssh-add ${GITLAB_RUNNER_KEY_FILE};
	fi
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
	. ${SSH_ENV} > /dev/null
    echo "SSH_ENV found ..."
    echo ${SSH_ENV}
	#ps ${SSH_AGENT_PID} doesn't work under cywgin
	ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
		start_agent;
		}
else
    start_agent;
fi

echo "List of keys of the SSH agent..."
/usr/bin/ssh-add -l
echo "SSH agent running."
