static const std::vector<msword2md::cpp::String> cmdinfo_doc_strings = {
{{termcolor::bold, termcolor::green}, "Description"},
{"\n\n"},
{"Show information about the manifest branch, current branch, or unmerged branches of all git repos\n"},
{"found in the manifest file. The information provided for each git repository are:\n\n"},
{"* The name\n\n"},
{"* The path\n\n"},
{"* The current revision\n\n"},
{"* The current branch\n\n"},
{"* The list of local branches\n\n"},
{{termcolor::bold, termcolor::green}, "Usage"},
{"\n\n"},
{termcolor::cyan, "esysrepo info [options ...]\n\n"},
{{termcolor::bold, termcolor::green}, "Options"},
{"\n\n"},
{"Currently, there is none.\n\n"},
{{termcolor::bold, termcolor::green}, "Examples"},
{"\n\n"},
{"When ran while working on the ESysRepo SW, it looked like this, and for conciseness, we will show\n"},
{"only the first few lines:\n\n"},
{"ESysRepo 0.1.0\n"},
{"\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Info ...\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Repo : esysbuild/dev\n"},
{"    Path           : .\n"},
{"    Cur rev.       : 1c755ba07965fdb0c43ae5f575abd9326bed1b83\n"},
{"    Cur branch     : master\n"},
{"    Manifest rev.  : refs/heads/master\n"},
{"    Local branches : 1\n"},
{"        [0] master               -> refs/remotes/origin/master\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Repo : esysbuild/esysbuild\n"},
{"    Path           : src/esysbuild\n"},
{"    Cur rev.       : da0312a7ee7d9f3a8f52b7873a94cd0250598324\n"},
{"    Cur branch     : master\n"},
{"    Manifest rev.  : refs/heads/master\n"},
{"    Local branches : 1\n"},
{"        [0] master               -> refs/remotes/origin/master\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Repo : esysrepo/esysrepo\n"},
{"    Path           : src/esysrepo\n"},
{"    Cur rev.       : ccd20a0490ed1e2fb4769ca8fcd9a22ba444ec8d\n"},
{"    Cur branch     : master\n"},
{"    Manifest rev.  : refs/heads/master\n"},
{"    Local branches : 1\n"},
{"        [0] master               -> refs/remotes/origin/master\n\n"},
{"\n"},
{"\n\n"},
};
