static const std::vector<msword2md::cpp::String> cmdinit_doc_strings = {
{{termcolor::bold, termcolor::green}, "Description"},
{"\n\n"},
{"Since this command initializes the current workspace, you will always start with this command. It\n"},
{"will create a folder called .esysrepo storing various configuration files as well as few git\n"},
{"repositories.\n\n"},
{"In its simplest form, the only parameter of the init command is the URL of the git repository where\n"},
{"the manifest is located. The steps then followed are:\n\n"},
{"* Clone the git repository with the manifest is a temporary folder inside the .esysrepo folder\n\n"},
{"* Detect the format of the manifest file. Is it following the Google repo tool manifest format or\n"},
{"the ESysRepo manifest format\n\n"},
{"* Depending on the manifest's format, it creates configurations files and moves the git repo with\n"},
{"the manifest to its final folder inside the .esysrepo folder\n\n"},
{"The folder's content of the folder .esysrepo is not secret, but it's not part of the public\n"},
{"interface of the tool and may change with different versions. So it's strongly advised to use only\n"},
{"the command line tool itself and not change by hand any of the files found in that folder, except\n"},
{"if explicitly documented.\n\n"},
{{termcolor::bold, termcolor::green}, "Usage"},
{"\n\n"},
{termcolor::cyan, "esysrepo init -u <URL> [options ...]\n\n"},
{{termcolor::bold, termcolor::green}, "Options"},
{"\n\n"},
{"Available options:\n\n"},
{"* --manifest-URL / -u <URL>: The URL of the git repository holding the manifest\n\n"},
{"* --manifest-branch / -b <BRANCH>: Manifest branch or revision to be checked out (default\n"},
{"\"master\")\n\n"},
{"* --manifest-name / -m <NAME>: Manifest file name used to initialize workspace (default\n"},
{"\"default.xml\").\n\n"},
{"* --google / -g: The manifest file has the Google repo tool format\n\n"},
{"* --output / -o <PATH>: The folder where to initialize the workspace (default is the current\n"},
{"folder)\n\n"},
{{termcolor::bold, termcolor::green}, "Examples"},
{"\n\n"},
{"To get the source code of ESysRepo, this would be the command line to use if using SSH (you need to\n"},
{"be a contributor):\n\n"},
{termcolor::cyan, "esysrepo init -u ssh://git@gitlab.com/libesys/esysbuild/manifest.git\n\n"},
{"Or simply using HTTPS, which will work for everyone:\n\n"},
{termcolor::cyan, "esysrepo init -u https://gitlab.com/libesys/esysbuild/manifest.git\n\n"},
{"\n"},
{"\n\n"},
};
