static const std::vector<msword2md::cpp::String> cmdlist_doc_strings = {
{{termcolor::bold, termcolor::green}, "Description"},
{"\n\n"},
{"List all pairs folder's name and git repo.\n\n"},
{{termcolor::bold, termcolor::green}, "Usage"},
{"\n\n"},
{termcolor::cyan, "esysrepo list [options ...]\n\n"},
{{termcolor::bold, termcolor::green}, "Options"},
{"\n\n"},
{"All available options are:\n\n"},
{"* --folder: the folder where the local workspace is located\n\n"},
{{termcolor::bold, termcolor::green}, "Examples"},
{"\n\n"},
{"Still on an ESysRepo SW development workspace:\n\n"},
{"ESysRepo 0.1.0\n"},
{"\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] List ...\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] path : name\n"},
{". : esysbuild/dev\n"},
{"src/esysbuild : esysbuild/esysbuild\n"},
{"src/esysrepo : esysrepo/esysrepo\n"},
{"extlib/pyswig : extlib/pyswig\n"},
{"src/esysbase : esysbase\n"},
{"src/esysfile : esysfile\n"},
{"src/esyslog : esyslog/syslog\n"},
{"src/esystest : esystest\n"},
{"src/esys_cmake_scripts : esys_cmake_scripts\n"},
{"src/esysmsvc : esysmsvc\n"},
{"extlib/dbg_log : extlib/dbg_log\n"},
{"extlib/libgit2 : libgit2/libgit2.git\n"},
{"extlib/libssh2 : libssh2/libssh2.git\n"},
{"extlib/nlohmann_json : nlohmann/json\n"},
{"extlib/spdlog : libESys/spdlog.git\n"},
{"src/esysrepo/doc/web/themes/hugo-theme-learn : matcornic/hugo-theme-learn.git\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] List done.\n"},
{"    elapsed time (s): 0.44\n\n"},
{"\n"},
{"\n\n"},
};
