static const std::vector<msword2md::cpp::String> cmdmanifest_doc_strings = {
{{termcolor::bold, termcolor::green}, "Description"},
{"\n\n"},
{"This command provides a utility to inspect and manipulate manifests. For the moment, the only\n"},
{"meaningful option is to be able to output a manifest where all revisions have been replaced by the\n"},
{"git commit hash found on the remote git repositories. Note that since esysrepo will check all the\n"},
{"remote git repositories, it may take some time, especially that this command is mono-threaded.\n\n"},
{{termcolor::bold, termcolor::green}, "Usage"},
{"\n\n"},
{termcolor::cyan, "esysrepo manifest [options ...]\n\n"},
{{termcolor::bold, termcolor::green}, "Options"},
{"\n\n"},
{"The available options are:\n\n"},
{"* --folder: the folder where the local workspace is located\n\n"},
{"* --output-file / -o <FILE> : the output file\n\n"},
{"* --revision-as-HEAD / -r: save all revisions as the git commit hash of the HEAD\n\n"},
{{termcolor::bold, termcolor::green}, "Examples"},
{"\n\n"},
{"Again taking a fresh workspace for SW development of ESysRepo, the following command and its result\n"},
{"are shown below:\n\n"},
{termcolor::cyan, "esysrepo manifest\n\n"},
{"ESysRepo 0.1.0\n"},
{"\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Manifest ...\n"},
{"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"},
{"<manifest>\n"},
{"    <remote name=\"origin\" fetch=\"ssh://git@gitlab.com/libesys\"/>\n"},
{"    <remote name=\"github\" fetch=\"https://github.com\"/>\n"},
{"    <default revision=\"refs/heads/master\" remote=\"origin\" sync-j=\"4\"/>\n"},
{"    <project path=\".\" name=\"esysbuild/dev\"/>\n"},
{"    <project path=\"src/esysbuild\" name=\"esysbuild/esysbuild\"/>\n"},
{"    <project path=\"src/esysrepo\" name=\"esysrepo/esysrepo\"/>\n"},
{"    <project path=\"extlib/pyswig\" name=\"extlib/pyswig\"/>\n"},
{"    <project path=\"src/esysbase\" name=\"esysbase\"/>\n"},
{"    <project path=\"src/esysfile\" name=\"esysfile\"/>\n"},
{"    <project path=\"src/esyslog\" name=\"esyslog/esyslog\"/>\n"},
{"    <project path=\"src/esystest\" name=\"esystest\"/>\n"},
{"    <project path=\"src/esys_cmake_scripts\" name=\"esys_cmake_scripts\"/>\n"},
{"    <project path=\"src/esysmsvc\" name=\"esysmsvc\"/>\n"},
{"    <project path=\"extlib/dbg_log\" name=\"extlib/dbg_log\"/>\n"},
{"    <project path=\"extlib/libgit2\" remote=\"github\" name=\"libgit2/libgit2.git\" revision=\"refs/tags/v1.1.0\"/>\n"},
{"    <project path=\"extlib/libssh2\" remote=\"github\" name=\"libssh2/libssh2.git\" revision=\"refs/tags/libssh2-1.9.0\"/>\n"},
{"    <project path=\"extlib/nlohmann_json\" remote=\"github\" name=\"nlohmann/json\" revision=\"refs/tags/v3.6.1\"/>\n"},
{"    <project path=\"extlib/spdlog\" remote=\"github\" name=\"libESys/spdlog.git\" revision=\"add_getter_for_console_mutex\"/>\n"},
{"    <project path=\"src/esysrepo/doc/web/themes/hugo-theme-learn\" remote=\"github\" name=\"matcornic/hugo-theme-learn.git\"/>\n"},
{"</manifest>\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Manifest done.\n"},
{"    elapsed time (s): 0.71\n\n"},
{"When using the option -r, the result is as follow:\n\n"},
{termcolor::cyan, "esysrepo manifest -r\n\n"},
{"ESysRepo 0.1.0\n"},
{"\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Manifest ...\n"},
{"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"},
{"<manifest>\n"},
{"    <remote name=\"origin\" fetch=\"ssh://git@gitlab.com/libesys\"/>\n"},
{"    <remote name=\"github\" fetch=\"https://github.com\"/>\n"},
{"    <default revision=\"refs/heads/master\" remote=\"origin\" sync-j=\"4\"/>\n"},
{"    <project path=\".\" name=\"esysbuild/dev\" revision=\"1c755ba07965fdb0c43ae5f575abd9326bed1b83\"/>\n"},
{"    <project path=\"src/esysbuild\" name=\"esysbuild/esysbuild\" revision=\"da0312a7ee7d9f3a8f52b7873a94cd0250598324\"/>\n"},
{"    <project path=\"src/esysrepo\" name=\"esysrepo/esysrepo\" revision=\"ccd20a0490ed1e2fb4769ca8fcd9a22ba444ec8d\"/>\n"},
{"    <project path=\"extlib/pyswig\" name=\"extlib/pyswig\" revision=\"10847cd47666ae9723c46ca455edb2a78f99f39f\"/>\n"},
{"    <project path=\"src/esysbase\" name=\"esysbase\" revision=\"b35c70845eca1040168f5afe491de96b564c746e\"/>\n"},
{"    <project path=\"src/esysfile\" name=\"esysfile\" revision=\"4ded443878e5d0269b88e3c532280df6c8ae1e17\"/>\n"},
{"    <project path=\"src/esyslog\" name=\"esyslog/esyslog\" revision=\"d558aef5e567bf0d6a0dfb27ee26efff0121508f\"/>\n"},
{"    <project path=\"src/esystest\" name=\"esystest\" revision=\"20cc5a62f7545e3a53abc882a8551d2416339d10\"/>\n"},
{"    <project path=\"src/esys_cmake_scripts\" name=\"esys_cmake_scripts\" revision=\"24d4793b932c3e0529db254b2910dc0d0a9ba3ad\"/>\n"},
{"    <project path=\"src/esysmsvc\" name=\"esysmsvc\" revision=\"f6e4aa2098257f43d65e670fb9a916ec791f98bb\"/>\n"},
{"    <project path=\"extlib/dbg_log\" name=\"extlib/dbg_log\" revision=\"112d7e5b0bc07c305dce2de2696ef7f6ea517a35\"/>\n"},
{"    <project path=\"extlib/libgit2\" remote=\"github\" name=\"libgit2/libgit2.git\" revision=\"7f4fa178629d559c037a1f72f79f79af9c1ef8ce\"/>\n"},
{"    <project path=\"extlib/libssh2\" remote=\"github\" name=\"libssh2/libssh2.git\" revision=\"42d37aa63129a1b2644bf6495198923534322d64\"/>\n"},
{"    <project path=\"extlib/nlohmann_json\" remote=\"github\" name=\"nlohmann/json\" revision=\"1126c9ca74fdea22d2ce3a065ac0fcb5792cbdaf\"/>\n"},
{"    <project path=\"extlib/spdlog\" remote=\"github\" name=\"libESys/spdlog.git\" revision=\"d32e9a4b1a829b75b1a4c09a466fe3c3500f2832\"/>\n"},
{"    <project path=\"src/esysrepo/doc/web/themes/hugo-theme-learn\" remote=\"github\" name=\"matcornic/hugo-theme-learn.git\" revision=\"d198cbe65f064575df1ab02415980d6e44363bf9\"/>\n"},
{"</manifest>\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Manifest done.\n"},
{"    elapsed time (s): 37.272\n\n"},
{"\n"},
{"\n\n"},
};
