static const std::vector<msword2md::cpp::String> cmdversion_doc_strings = {
{{termcolor::bold, termcolor::green}, "Description"},
{"\n\n"},
{"Print the version of ESysRepo and few used libraries.\n\n"},
{{termcolor::bold, termcolor::green}, "Usage"},
{"\n\n"},
{termcolor::cyan, "esysrepo version [options ...]\n\n"},
{{termcolor::bold, termcolor::green}, "Options"},
{"\n\n"},
{"Currently, there is none.\n\n"},
{{termcolor::bold, termcolor::green}, "Examples"},
{"\n\n"},
{"The output from the first released version of ESysRepo is shown below.\n\n"},
{"ESysRepo 0.1.0\n"},
{"\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Version ...\n"},
{"ESysRepo       0.1.0\n"},
{"ESysRepo lib   0.0.1\n"},
{"libgit2        1.1.0\n"},
{"libssh2        1.9.0_DEV\n"},
{ "["}, 
{ termcolor::color<112, 173, 71>, "info", termcolor::reset}, 
{"] Version done.\n"},
{"    elapsed time (s): 0.8\n\n"},
{"\n"},
{"\n\n"},
};
