static const std::vector<msword2md::cpp::String> usage_doc_strings = {
{"The command-line tool is very similar to both the [Google\n"},
{"repo](https://gerrit.googlesource.com/git-repo/) tool and [git-repo](https://git-repo.info). Since\n"},
{"it's already known and well done, there was no point in being creative on that front. Note that\n"},
{"esysrepo implements only the main commands for now, typically with fewer options and some\n"},
{"additions. But it should be very straightforward for anyone who used any of the tools mentioned\n"},
{"above.\n\n"},
{"Every command follows the same pattern:\n\n"},
{termcolor::cyan, "esysrepo <COMMAND> [options …]\n\n"},
{"The list of the supported commands is:\n\n"},
{"* init\n\n"},
{"* sync\n\n"},
{"* info\n\n"},
{"* status\n\n"},
{"* list\n\n"},
{"* manifest\n\n"},
{"* version\n\n"},
{"* help\n\n"},
{"\n"},
{"\n\n"},
};
